#!/bin/bash
for uifile in iknow/ui/*.ui
do
    uifilename="${uifile##*/}"
    echo -e "$uifile > iknow/ui/Ui_${uifilename%.[^.]*}.py"
    pyside-uic "$uifile" > "iknow/ui/Ui_${uifilename%.[^.]*}.py"
done
